### PR TITLE
Finished #38 As a visitor I want to be able to hide nested comments

### PR DESCRIPTION
**Pull request by wildtype**
The fold-unfold component works with little change to HTML structure in comments. Current comments layout, where every comments is in the same level is maintained.

I also setup basic JS development environment in folder `js/`. That folder and its content should be removable without interfering other part. Instructions to test and build/compile the code is available in `js/README.md`. Compiled js is placed in `app/assets/js/application.js`.

For the time being, I committed the compiled js to scm. The code can be deployed directly to heroku without compiling first. I've yet to find the way to integrate js compilation with heroku's deployment process. We should fix this in the future.

### CODE REVIEW

**Comment by nsiregar** [comment]
Btw ane baru sadar ini ternyata mau merge ke master, ga ke dev dulu?

**Comment by wildtype** [comment]
@nsiregar Wah, saya pikir branch yang dev itu setelah selesai pr & dimerge akan hilang, jadi saya prnya ke master.. PR di github bisa ke branch selain master ya?

**Comment by nsiregar** [comment]
@wildtype bisa kemaren @aancw juga begini terus dirubah ke dev. btw ini ane nyoba ngikutin yang model ini https://nvie.com/posts/a-successful-git-branching-model/

**Comment by wildtype** [comment]
@nsiregar Boleh tuh modelnya. Berarti setiap commit melewati 2 kali PR ya? Dari feature branch ke development, dari development ke master?

**Comment by nsiregar** [comment]
kalo ane sih merge ke developmentnya di lokal, apa kita bikin gitu aja ya biar ada kegiatan PR

**Pull request merged**
